name: 'Maximize disk space'
description: 'Maximize the disk space of GitHub Actions.'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  use-system-docker:
    description: 'Use the system built-in docker to clean the images.'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Before clean
      shell: bash
      run: df -h

    - name: Maximize disk space
      shell: bash
      run: |
        # Function to safely delete contents of a directory if it exists
          safe_delete() {
          local dir="$1"
          [ -d "$dir" ] && sudo find "$dir" -mindepth 1 -delete
        }
        
        # Remove unnecessary software
          safe_delete /usr/local
          safe_delete /usr/lib/google-cloud-sdk
          safe_delete /usr/share/dotnet
          safe_delete /usr/share/swift
          safe_delete /opt/az
          safe_delete /opt/google
          safe_delete /opt/microsoft
          safe_delete /opt/pipx
          safe_delete /opt/hostedtoolcache
          
          # Remove Docker images
          download_docker_binary() {
          local docker_version="24.0.6"
          local arch="x86_64"
          [ "$(dpkg --print-architecture)" = "amd64" ] || arch="aarch64"
          curl https://download.docker.com/linux/static/stable/${arch}/docker-${docker_version}.tgz | \
          sudo tar zxv -C /usr/bin/ docker/docker --strip-components 1
        }
          
          [ "${{ inputs.use-system-docker }}" = "true" ] || download_docker_binary
          sudo docker image prune -af
          
          # Exit without error
          exit 0

    - name: After clean
      shell: bash
      run: df -h
