name: 'Maximize disk space'
description: 'Maximize the disk space of GitHub Actions.'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  use-system-docker:
    description: 'Use the system built-in docker to clean the images.'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Before clean
      shell: bash
      run: df -h

    - name: Remove unnecessary software
      shell: bash
      run: |
        # Remove unnecessary software
        rm -rf /usr/local
        rm -rf /usr/lib/google-cloud-sdk
        rm -rf /usr/share/dotnet
        rm -rf /usr/share/swift
        rm -rf /opt/az
        rm -rf /opt/google
        rm -rf /opt/microsoft
        rm -rf /opt/pipx
        rm -rf /opt/hostedtoolcache
        
        # Exit without error
        exit 0
    - name: Remove Docker images
      shell: bash
      run: |
        # Remove Docker images
        download_docker_binary() {
          local docker_version="24.0.6"
          local arch="x86_64"
          [ "$(dpkg --print-architecture)" = "amd64" ] || arch="aarch64"
          curl https://download.docker.com/linux/static/stable/${arch}/docker-${docker_version}.tgz | \
          sudo tar zxv -C /usr/bin/ docker/docker --strip-components 1
        }
        
        [ "${{ inputs.use-system-docker }}" = "true" ] || download_docker_binary
        sudo docker image prune -af
        
        # Exit without error
        exit 0

    - name: After clean
      shell: bash
      run: df -h
